# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOPRIVATE: github.com/huski-inc
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25'

      - name: Install dependencies
        run: go mod download

      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: 'latest'
          install-go: false
          checks: 'all'

      - name: Build
        run: go build -v ./...

      # - name: Test
      #   run: go test -gcflags=all=-l -v --count=1 -coverprofile=coverage.txt -covermode=atomic ./...
